# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Problem without Promise' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 3.4'
  pod 'SwiftyJSON'

  # Pods for Problem without Promise

  target 'Problem without PromiseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Problem without PromiseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
